### ISSUE TITLE
Installing Zenity clears system path variable

### ISSUE THREAD

**Issue by ghost** [kvaps/zenity-windows#1]
Installing this application deleted the entire system path environment variable which broke connection to PowerShell and other command line applications. You need to fix how you handle the registry or whatever script you use to add your variable to path. That's a HUGE problem.

**Comment by IceSandwich** [comment]
I installed it before seeing this issue. I lost all stuffs in path environment variable. Now i fail to recover my system. It's really a huge problem.

**Comment by kvaps** [comment]
Hey guys! Thanks for reporting!
Unfortunately I have no windows for couple of years, and I not maintain this project anymore.

Adding the huge warning to [releases page](https://github.com/kvaps/zenity-windows/releases/tag/v3.20.0-1) that is all what I can do for now. Sorry 🙄

**UPD:** As about recovery, I think that **"System Restore"** windows tool should help you to fix your environment to the previous state when zenity for windows wasn't installed yet.

**Comment by jackusay** [comment]
This one can use Zenity.exe directly without install: [maravento/winzenity: Zenity Portable for Windows](https://github.com/maravento/winzenity)
version:3.6.0
size:1.86MB

and this project only provide Win32 installer file.
**If you already install this project**, please upload Zenity.exe before restore your system...
So others can use it directly...

Or maybe you can try to unpack this installer...

**Comment by ncruces** [comment]
Please consider [github.com/ncruces/zenity](https://github.com/ncruces/zenity#readme).

**Comment by jleaders** [comment]
@kvaps  You need to take this repo down, you can't essentially be destroying systems and then saying "oops, sorry run system recovery"
You will be reported to github for malicious software

**Comment by kvaps** [comment]
You're right, I will remove the binary since there is reliable fork of zenity for windows

**Comment by kvaps** [comment]
Release removed, so issue can be closed
